version: '3.4'

services:
  englishcentralmanagement:
    image: ${DOCKER_REGISTRY-}englishcentralmanagement
    build:
      context: .
      dockerfile: EnglishCentralManagement/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: EnglishCentreDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"